import type {
  LazyExoticComponent,
  ComponentType as ReactComponentType,
  ReactNode,
} from "react";

/**
 * Component type for RSC support
 */
export type ComponentType = "server" | "client";

/**
 * Route configuration interface with RSC support
 */
export interface RouteConfig {
  /** Lazy component - always defined, even for server components (they may contain client boundaries) */
  component: LazyExoticComponent<ReactComponentType<any>>;
  /** Whether this is a server or client component */
  componentType: ComponentType;
  /** Lazy layout for client layouts, null for server layouts */
  layout?: LazyExoticComponent<
    ReactComponentType<{ children: ReactNode }>
  > | null;
  /** Layout component type */
  layoutType?: ComponentType;
  /** Client parent layouts (lazy loaded) */
  parentLayouts?: LazyExoticComponent<
    ReactComponentType<{ children: ReactNode }>
  >[];
  /** Types of parent layouts */
  parentLayoutTypes?: ComponentType[];
  isDynamic?: boolean;
  dynamicSegments?: string[];
}

/**
 * Virtual routes - placeholder export for TypeScript
 * The actual routes are generated by the bundler plugin at build time
 */
export const routes: Record<string, RouteConfig> = {};
