import type { ComponentType, ReactNode, LazyExoticComponent } from "react";

/**
 * Route configuration interface
 */
export interface RouteConfig {
  component: LazyExoticComponent<ComponentType<any>>;
  layout?: LazyExoticComponent<ComponentType<{ children: ReactNode }>>;
  parentLayouts?: LazyExoticComponent<ComponentType<{ children: ReactNode }>>[];
  isDynamic?: boolean;
  dynamicSegments?: string[];
}

/**
 * Virtual routes - placeholder export for TypeScript
 * The actual routes are generated by the bundler plugin at build time
 */
export const routes: Record<string, RouteConfig> = {};
